# Generated by Django 2.1 on 2018-09-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('CAR', 'Car'), ('TRK', 'Truck'), ('PLN', 'Airplane')], max_length=3)),
                ('number_of_doors', models.PositiveIntegerField()),
                ('number_of_wheels', models.PositiveIntegerField()),
                ('number_of_airbags', models.PositiveIntegerField()),
                ('seating_capacity', models.PositiveIntegerField()),
                ('steering_type', models.CharField(max_length=200)),
                ('engine_type', models.CharField(max_length=200)),
                ('engine_power', models.CharField(max_length=200)),
                ('extras', models.TextField()),
                ('number_of_drivers', models.PositiveIntegerField()),
                ('number_of_engines', models.PositiveIntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturers.Manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
