# Generated by Django 2.1 on 2018-09-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinformation',
            name='engine_power',
        ),
        migrations.RemoveField(
            model_name='vehicleinformation',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='vehicleinformation',
            name='number_of_drivers',
        ),
        migrations.RemoveField(
            model_name='vehicleinformation',
            name='steering_type',
        ),
    ]
