# Generated by Django 2.1 on 2018-09-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('mode', models.CharField(choices=[('CR', 'Credit'), ('DB', 'Debit')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('available_amount', models.FloatField()),
                ('total_spent', models.FloatField()),
                ('total_earned', models.FloatField()),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='manufacturers.Manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('transactions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='currency.Transactions')),
                ('timestamp', models.DateTimeField()),
                ('reference_number', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.VehicleInformation')),
            ],
            options={
                'abstract': False,
            },
            bases=('currency.transactions', models.Model),
        ),
        migrations.AddField(
            model_name='transactions',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturers.Manufacturer'),
        ),
    ]
