# Generated by Django 2.1 on 2018-09-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_expenditures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='currency.Wallet'),
            preserve_default=False,
        ),
    ]
