# Generated by Django 2.1 on 2018-09-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_historicalexpenditures_historicalsales_historicaltransactions_historicalwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwallet',
            name='available_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalwallet',
            name='total_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalwallet',
            name='total_spent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='available_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_spent',
            field=models.FloatField(default=0),
        ),
    ]
